version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ps
      POSTGRES_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - postgres_volume: /var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bash -c "bundle e rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/myapp

volumes:
  postgres_volume:
