services:
  backend:
    image: postgres
    environment:
      POSTGRES_USER: ps
      POSTGRES_PASSWORD: password
      TZ: "Asiz/Tokyo"
    networks:
      - back-tier
  frontend:
    build: 
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bash -c "bundle e rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - .:/myapp
    environment:
      - DB_HOST=backend
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
    networks:
      - front-tier
      - back-tier

networks:
  front-tier: {}
  back-tier: {}

